In [ ]:
import numpy as np

n = int(input('Enter the length of dataset: '))

dist = np.zeros(shape=(n, n))

index_dict = {key: [key] for key in range(n)}
index_dict_ans = {key: [str('P' + str(key))] for key in range(n)}

dist = np.array([
    [0, 0, 0, 0, 0],
    [9, 0, 0, 0, 0],
    [3, 7, 0, 0, 0],
    [6, 5, 9, 0, 0],
    [11, 10, 2, 8, 0]
])

m = 0
final_pattern = []
final_pattern_ans = []

while n != 1:
    min_list = []
    for i in range(1, n):
        for j in range(i):
            min_list.append(dist[i, j])
    print(min_list)
    min_val = np.min(min_list)
    print("Minimum Value: ",min_val)

    merge_index = np.where(dist == min_val)
    list_of_index = list(zip(merge_index[0], merge_index[1]))

    for index in list_of_index:
        index = list(index)

    index_dict[np.min(index)].append(np.max(index))
    final_pattern.append(index_dict[np.min(index)].copy())

    for k in index_dict_ans[np.max(index)]:
        index_dict_ans[np.min(index)].append(k)

    final_pattern_ans.append(index_dict_ans[np.min(index)].copy())

    index_dict.pop(np.max(index))
    index_dict_ans.pop(np.max(index))

    temp_val_list = list(index_dict.values())
    temp_val_list_ans = list(index_dict_ans.values())
    n = n - 1

    index_dict_new = {key: temp_val_list[i] for i, key in enumerate(range(n))}
    index_dict_ans_new = {key: temp_val_list_ans[i] for i, key in enumerate(range(n))}

    index_dict = index_dict_new
    index_dict_ans = index_dict_ans_new

    new_dist = np.zeros(shape=(n, n))

    for i in range(n):
        for j in range(i+1):
            new_dist[i, j] = dist[i, j]

    print(new_dist)
    key_list = list(index_dict.keys())
    val_list = list(index_dict.values())
    ind = val_list.index(final_pattern[m])

    k = key_list[ind]

    for i in range(k):
        new_dist[k, i] = np.max([dist[s, i] for s in index])

    for i in range(np.max(index), n):
        for j in range(n):
            new_dist[i, j] = dist[i + 1, j]

    for i in range(n):
        new_dist[i, i] = 0

    m = m + 1
    dist = new_dist

print('Final Pattern: ', final_pattern_ans)

Enter the length of dataset: 5
[9, 3, 7, 6, 5, 9, 11, 10, 2, 8]
Minimum Value:  2
[[0. 0. 0. 0.]
 [9. 0. 0. 0.]
 [3. 7. 0. 0.]
 [6. 5. 9. 0.]]
[9.0, 11.0, 10.0, 6.0, 5.0, 9.0]
Minimum Value:  5.0
[[ 0.  0.  0.]
 [ 9.  0.  0.]
 [11. 10.  0.]]
[9.0, 11.0, 10.0]
Minimum Value:  9.0
[[0. 0.]
 [9. 0.]]
[11.0]
Minimum Value:  11.0
[[0.]]
Final Pattern:  [['P2', 'P4'], ['P1', 'P3'], ['P0', 'P1', 'P3'], ['P0', 'P1', 'P3', 'P2', 'P4']]
